### ISSUE TITLE
Historic Lake Bonneville layer error in ArcGIS Pro

### ISSUE THREAD

**Issue by nathankota** [agrc/open-sgid#17]
Open SGID user:

> I just added a layer from the OpenSGID connection, and it looks like there is a problem with it.  It's the layer:  opensgid.agrc.historic_lake_bonneville.  When I drag it into a map, nothing is displayed.  When I attempt to open the attribute table, I get this message in ArcGIS Pro:

![image](https://user-images.githubusercontent.com/15659642/84205637-bfd6c480-aa6a-11ea-8f8e-5c11c7edc1ac.png)

**Comment by steveoh** [comment]
This is a little troubling since make valid is already run during the import/update process. 

I will try to reimport it tonight and if that fails we will need to make changes to the source data.

**Comment by authalic** [comment]
I'm the user who reported that error to Nathan.  He asked me to submit more detail.
I'm using ArcGIS Pro 2.5.1 on a Dell ZBook with a 2.8 GHz Intel Xeon processor, Windows 10 Pro, with 32 GB RAM.  I have been using OpenSGID for months, and probably access layers every day I work.  This is the first time I have encountered this error.

**Comment by authalic** [comment]
I'm curious if you're using the `ST_MakeValid` function in PostGIS?  I ran into something like this, earlier in the year, where PostGIS was saying a polygon was a valid geometry, but Esri software was saying it was not.  It turns out that they use two different definitions of validity.  There is a note at the bottom of this article that explains it somewhat:  https://postgis.net/workshops/postgis-intro/validity.html

> The “banana polygon” (or “inverted shell”) is a case where the OGC topology model for valid geometry and the model used internally by ESRI differ. The ESRI model considers rings that touch to be invalid, and prefers the banana form for this kind of shape. The OGC model is the reverse. Neither is “correct”, they are just different ways to model the same situation.

**Comment by steveoh** [comment]
Yes, we run the [make_valid in postgis](https://github.com/agrc/open-sgid/blob/master/src/cloudb/__main__.py#L479-L492). We ran into the same issue early on where mssql server + enterprise gdb says every layer is valid but postgis disagreed. 

I opened an issue with the gdal folks since that is how we sync the data but my assumptions were wrong and the core problem is the difference in isvalid from the two groups. https://github.com/OSGeo/gdal/issues/2086#issuecomment-567675209

**Comment by steveoh** [comment]
Reimporting the layer has fixed the shape integrity error. Please check that it is also working in your environment. I will keep an eye on things. Thanks for the issue!
